2021-12-29 11:48:51 main.py 293 thead_start program_end             Public.program_end(e)\n (<class 'udp_loglib.Public'>, Exception(2, [2])) {}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('Traceback (most recent call last):\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('  File "c:\\Users\\test2\\Desktop\\testplaatform1025\\Master\\testplatform\\case_test\\main.py", line 291, in thead_start\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('    main()\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('  File "c:\\Users\\test2\\Desktop\\testplaatform1025\\Master\\testplatform\\case_test\\main.py", line 278, in main\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('    Public.program_end(e) # 异常时直接结束\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('  File "c:\\Users\\test2\\Desktop\\testplaatform1025\\Master\\testplatform\\py_lib\\FuncLog.py", line 59, in run\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('    return func(*args, **kwargs)\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('  File "c:\\Users\\test2\\Desktop\\testplaatform1025\\Master\\testplatform\\udp_loglib.py", line 132, in program_end\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('    raise exc\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('  File "c:\\Users\\test2\\Desktop\\testplaatform1025\\Master\\testplatform\\case_test\\main.py", line 273, in main\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('    mod.main() # 执行用例的 main 方法\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('  File "c:\\Users\\test2\\Desktop\\testplaatform1025\\Master\\testplatform\\case_test\\testcase/Sw_MVCU/Cfg2_SwITC_MVCU_1517.py", line 39, in main\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('    step1()\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('  File "c:\\Users\\test2\\Desktop\\testplaatform1025\\Master\\testplatform\\case_test\\testcase/Sw_MVCU/Cfg2_SwITC_MVCU_1517.py", line 32, in step1\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ("    caseFunc.vm_build_update('2', 'VCU_MVCU_SwITC_1517001')\n",) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('  File "c:\\Users\\test2\\Desktop\\testplaatform1025\\Master\\testplatform\\case_test\\caseFunc.py", line 201, in vm_build_update\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ("    form.update('auto', 0, slots)\n",) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('  File "c:\\Users\\test2\\Desktop\\testplaatform1025\\Master\\testplatform\\RUT\\light_update.py", line 335, in update\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('    raise Exception(rt_code, rt_list)\n',) {'mode': 2}
2021-12-29 11:48:51 udp_loglib.py 112 program_end mPrint             mPrint(line, mode=2)\n ('Exception: (2, [2])\n',) {'mode': 2}
